# Change these first
owner: upptime # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: ALYF Website
    url: https://alyf.de
  - name: ALYF Cloud
    url: $ALYF_CLOUD_URL
  - name: ERPNext (intern)
    url: $ALYF_ERPNEXT_URL


status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://alyf.de/logo.png
  name: Status
  introTitle: "Systemstatus der ALYF GmbH"
  introMessage: "Hier sehen Sie welche unserer Systeme online sind und wo es ggf. gerade Probleme gibt."
  navbar:
    - title: Website
      href: https://alyf.de
    - title: GitHub
      href: https://github.com/alyf-de

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
